# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).

basic = Package.create(name: "Basic Single Pass", price: 15)
first = Package.create(name: "First Workshop Pass", price: 10)
four = Package.create(name: "4-Workshop Pass", price: 50)
teacher_names = %w(cedric mark chris terence adrian)
teacher_names.each do |teacher_name| 
  teacher = Teacher.create!(name: teacher_name)
  instance_variable_set("@#{teacher_name}", teacher)
end

def create_attendance(workshop, student_name)
  student = Student.where(name: student_name.capitalize).first_or_create
  Attendance.create(workshop: workshop, student: student)
  student.update_attributes!(passes_remaining: student.passes_remaining - 1)
  ClassPassTransaction.create!(student: student, delta: -1)
end

def create_purchase(package, student_name)
  student = Student.where(name: student_name.capitalize).first_or_create
  purchase = Purchase.create!(package: package, student: student)
  if purchase.package.name == "4-Workshop Pass"
    student.update_attributes!(passes_remaining: student.passes_remaining + 4)
    ClassPassTransaction.create!(student: student, delta: 4)
  else
    student.update_attributes!(passes_remaining: student.passes_remaining + 1)
    ClassPassTransaction.create!(student: student, delta: 1)
  end 
end

create_purchase(four, "Fiona")
create_purchase(four, "Clemson")
create_purchase(four, "Akane")
create_purchase(four, "Victor")
create_purchase(four, "Red")
create_purchase(four, "Akane")
create_purchase(four, "Clemson")
create_purchase(four, "Jo")
create_purchase(four, "Baris")
create_purchase(four, "Victor")
create_purchase(four, "Red")
create_purchase(four, "Clemson")
create_purchase(four, "Akane")
create_purchase(four, "Victor")
create_purchase(four, "Henry")
create_purchase(four, "Using")
create_purchase(four, "Danny")
create_purchase(four, "Jo")
create_purchase(four, "Red")
create_purchase(four, "Fiona")
create_purchase(four, "Clemson")
create_purchase(four, "Akane")

workshop = Workshop.create(teachers: [@mark], held_on: Date.parse('2016-08-04'))
create_attendance(workshop, "fiona")
create_attendance(workshop, "clemson")
create_attendance(workshop, "akane")
workshop = Workshop.create(teachers: [@terence], held_on: Date.parse('2016-08-11'))
create_attendance(workshop, "clemson")
create_attendance(workshop, "akane")
workshop = Workshop.create(teachers: [@chris], held_on: Date.parse('2016-08-18'))
create_attendance(workshop, "fiona")
create_attendance(workshop, "clemson")
create_attendance(workshop, "akane")
create_attendance(workshop, "victor")
  
workshop = Workshop.create(teachers: [@cedric], held_on: Date.parse('2016-08-25'))
    create_attendance(workshop, "Baris")
    create_purchase(first, "baris")
    create_attendance(workshop, "jo")
    create_attendance(workshop, "Akane")
    create_attendance(workshop, "Clemson")
    create_attendance(workshop, "Joyce")
    create_attendance(workshop, "Bill")
    create_purchase(basic, "bill")
    create_attendance(workshop, "Ekl")
    create_purchase(basic, "ekl")
    create_attendance(workshop, "Victor")
    create_attendance(workshop, "Red")
workshop = Workshop.create(teachers: [@terence], held_on: Date.parse('2016-09-01'))
    create_attendance(workshop, "baris")
    create_purchase(basic, "baris")
    create_attendance(workshop, "Jo")
    create_attendance(workshop, "Joyce")
    create_attendance(workshop, "Fiona")
    create_attendance(workshop, "Kurt")
    create_purchase(basic, "kurt")
    create_attendance(workshop, "Clemson")
    create_attendance(workshop, "Victor")
    create_attendance(workshop, "Red")
    create_attendance(workshop, "Akane")
workshop = Workshop.create(teachers: [@mark], held_on: Date.parse('2016-09-08'))
    create_attendance(workshop, "Joyce")
    create_attendance(workshop, "Jo")
    create_attendance(workshop, "Baris")
    create_purchase(basic, "baris")
    create_attendance(workshop, "Clemson")
    create_attendance(workshop, "Victor")
    create_attendance(workshop, "Akane")
    create_attendance(workshop, "Fiona")
    create_attendance(workshop, "Red")
workshop = Workshop.create(teachers: [@chris], held_on: Date.parse('2016-09-15'))
    create_attendance(workshop, "Henry")
    create_purchase(basic, "henry")
    create_attendance(workshop, "Joyce")
    create_attendance(workshop, "Red")
    create_attendance(workshop, "Clemson")
    create_attendance(workshop, "Akane")
    create_attendance(workshop, "Victor")
    create_purchase(basic, "victor")
    create_attendance(workshop, "Baris")
workshop = Workshop.create(teachers: [@cedric], held_on: Date.parse('2016-09-22'))
    create_attendance(workshop, "Bill")
    create_purchase(basic, "bill")
    create_attendance(workshop, "Henry")
    create_purchase(basic, "henry")
    create_attendance(workshop, "Victor")
    create_attendance(workshop, "Red")
    create_attendance(workshop, "Clemson")
    create_attendance(workshop, "Jo")
    create_attendance(workshop, "Joyce")
    create_attendance(workshop, "Akane")
workshop = Workshop.create(teachers: [@terence], held_on: Date.parse('2016-09-29'))
    create_attendance(workshop, "jo")
    create_attendance(workshop, "joyce")
    create_attendance(workshop, "clemson")
    create_attendance(workshop, "victor")
    create_attendance(workshop, "akane")
    create_attendance(workshop, "red")
workshop = Workshop.create(teachers: [@mark], held_on: Date.parse('2016-10-06'))
    create_attendance(workshop, "joyce")
    create_attendance(workshop, "danny")
    create_purchase(first, "danny")
    create_attendance(workshop, "using")
    create_purchase(first, "using")
    create_attendance(workshop, "akane")
    create_attendance(workshop, "red")
    create_attendance(workshop, "clemson")
    create_attendance(workshop, "victor")
workshop = Workshop.create(teachers: [@chris], held_on: Date.parse('2016-10-13'))
    create_attendance(workshop, "danny")
    create_attendance(workshop, "using")
    create_attendance(workshop, "akane")
    create_attendance(workshop, "victor")
    create_attendance(workshop, "clemson")
    create_attendance(workshop, "red")
    create_attendance(workshop, "fiona")
    create_purchase(basic, "fiona")
    create_attendance(workshop, "joyce")
    create_attendance(workshop, "henry")
workshop = Workshop.create(teachers: [@cedric], held_on: Date.parse('2016-10-20'))
    create_attendance(workshop, "Fiona")
    create_attendance(workshop, "Red")
    create_attendance(workshop, "Akane")
    create_attendance(workshop, "Clemson")
    create_attendance(workshop, "Victor")
    create_attendance(workshop, "using")
workshop = Workshop.create(teachers: [@chris, @cedric], held_on: Date.parse('2016-10-27'))
    create_attendance(workshop, "Joyce")
    create_attendance(workshop, "Clemson")
    create_attendance(workshop, "Victor")
    create_attendance(workshop, "Akane")
    create_attendance(workshop, "Red")
workshop = Workshop.create(teachers: [@terence], held_on: Date.parse('2016-11-03'))
    create_attendance(workshop, "Clemson")
    create_attendance(workshop, "Akane")
    create_attendance(workshop, "Henry")
    create_attendance(workshop, "Victor")
    create_attendance(workshop, "Red")
    create_attendance(workshop, "Joyce")
workshop = Workshop.create(teachers: [@mark], held_on: Date.parse('2016-11-10'))
    create_attendance(workshop, "joyce")
    create_attendance(workshop, "clemson")
    create_attendance(workshop, "akane")
    create_attendance(workshop, "victor")
    create_attendance(workshop, "henry")

